 let skillset = ["Batting" ,"Bowling" ,"Fielding"]
// let data = {
// 	first_name:"Sachin",
// 	last_name:"Tendulkar",
// 	phone:9900990099,
// 	skills:skillset
// }


// let data_json = JSON.stringify(data)
// console.log(typeof(data))
// console.log(data_json)



// let st_data = {
// 	first_name:"Sachin",
// 	last_name:"Tendulkar",
// 	phone:9900990099,
// 	skills:skillset
// }


// localStorage.setItem("Laptop", "Dell")
// localStorage.setItem("Phone", "iPhone")
// localStorage.setItem("TV", "Sony")

// let dta = JSON.stringify(st_data)

// localStorage.removeItem("user", dta)

// console.log(localStorage.key(0))


let st_data = {
	first_name:"Sachin",
	last_name :"Tendulkar",
	phone     : 9900990099,
	skills    : skillset
}