let number1 = 2
let number2 = 3
let output

// Assignment
//number1 = number2

// Assignment
	// +, - , *, /, %, **

/*
	output = "ABCD"
	console.log(output)
 	output = number1 + number2
	console.log(output)
	output = number1 - number2
	console.log(output)
	output = number1 * number2
	console.log(output)
	output = number1 / number2
	console.log(output)
	output = number1 % number2
	console.log(output)
	output = number1 ** number2 

	
Comparision
	==

	!=
	
	>
	
	<
	
	
	>=  
	
	
	<=
	
	*/
	
let a = 20
let b = '20'
	
	
/* 	console.log('a is equal to b ==>', a == b)
	console.log('a is not equal b ==>', a != b)
	console.log('a is greater than b ==>', a > b)
	console.log('a is greater than or equal to b ==>', a >= b) */
	
	
//	console.log(typeof(a), typeof(b))
//	console.log('a is equal to b ==>', a === b)
//	console.log(`${a} is not equal to ${b} with !== ==>`, a !== b)
//	console.log(`${a} is not equal to ${b} with != ==>`, a != b)
//	console.log(`${a} is equal to ${b} with == ==>`, a == b)


let c = a == b	
let d = true
let e = true	
let f = true
let g = false	
/* 
	console.log("and ", c && d && e && f && g)
	console.log("or ", c || d || e || f || g)
	console.log("negation ", !f) */


//let variable = false, 0, NaN, null, undefined, '', "", ``, 

/* let variable = " "


if (variable)
{
	console.log("yes")
}
else{
	console.log("no")
}



a = 10

	console.log(a--)
	
console.log(++a)
console.log(a)
 */
 
a = 30

a > 50 ? console.log("Yes it is") : console.log("No, Its not") 